// <auto-generated />
using System;
using ElsaEdiBackend.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElsaEdiBackend.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221128011643_Initialx")]
    partial class Initialx
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.11");

            modelBuilder.Entity("ElsaEdiBackend.Domain.WorkflowDefinitions.WorkflowDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsLatest")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VersionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkflowDefinitions");
                });

            modelBuilder.Entity("ElsaEdiBackend.Domain.WorkflowInstances.WorkflowInstance", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowDefinitionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowDefinitionId");

                    b.ToTable("WorkflowInstance");
                });

            modelBuilder.Entity("ElsaEdiBackend.Domain.WorkflowDefinitions.WorkflowDefinition", b =>
                {
                    b.OwnsMany("ElsaEdiBackend.Domain.WorkflowDefinitions.AccessList", "Permissions", b1 =>
                        {
                            b1.Property<string>("WorkflowDefinitionId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("TEXT")
                                .HasColumnName("permission_createdon");

                            b1.Property<string>("UserName")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("permission_username");

                            b1.HasKey("WorkflowDefinitionId", "Id");

                            b1.ToTable("AccessList");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowDefinitionId");
                        });

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("ElsaEdiBackend.Domain.WorkflowInstances.WorkflowInstance", b =>
                {
                    b.HasOne("ElsaEdiBackend.Domain.WorkflowDefinitions.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany("WorkflowInstances")
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("ElsaEdiBackend.Domain.WorkflowDefinitions.WorkflowDefinition", b =>
                {
                    b.Navigation("WorkflowInstances");
                });
#pragma warning restore 612, 618
        }
    }
}
